# Generated by Django 2.2.3 on 2019-07-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190620_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m')),
                ('address', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
    ]
