# Generated by Django 2.2.4 on 2019-08-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_globalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
