# Generated by Django 2.2.4 on 2019-08-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190803_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image',
            new_name='_image',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='image_thumb',
            new_name='_image_thumb',
        ),
    ]
