# Generated by Django 2.2.4 on 2019-08-03 08:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190803_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='_image_thumb',
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.save_image),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.save_thumb),
        ),
    ]
