# Generated by Django 2.2.3 on 2019-07-15 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiry', '0005_auto_20190715_0844'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=150, null=True)),
                ('check_in_date', models.DateTimeField(blank=True, null=True)),
                ('check_out_date', models.DateTimeField(blank=True, null=True)),
                ('listing_position_number', models.PositiveIntegerField(blank=True, null=True)),
                ('room_category_and_rates', models.TextField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('EXECUTING', 'Executing'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ota_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.OTA')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
