# Generated by Django 2.2.12 on 2020-05-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("document_type", models.CharField(blank=True, max_length=10)),
                ("document_id", models.IntegerField(blank=True)),
                ("fileUrl", models.CharField(blank=True, max_length=10)),
                ("label", models.TextField(blank=True)),
                ("language", models.CharField(blank=True, max_length=10)),
            ],
        )
    ]
