# Generated by Django 2.2.12 on 2020-05-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("asset", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="document", name="fileUrl", field=models.URLField(blank=True)
        )
    ]
