# Generated by Django 2.2.12 on 2020-05-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("asset", "0003_document_downloadurl")]

    operations = [
        migrations.AddField(
            model_name="document", name="previewUrl", field=models.URLField(blank=True)
        )
    ]
