# Generated by Django 2.2.12 on 2020-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("asset", "0005_auto_20200514_1221")]

    operations = [
        migrations.AddField(
            model_name="document", name="downloadUrl", field=models.URLField(blank=True)
        ),
        migrations.AddField(
            model_name="document", name="fileUrl", field=models.URLField(blank=True)
        ),
        migrations.AddField(
            model_name="document", name="previewUrl", field=models.URLField(blank=True)
        ),
    ]
