# Generated by Django 2.2.12 on 2020-05-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='fileUrl',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
