# Generated by Django 2.2.2 on 2019-06-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20190607_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ota',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-id',)},
        ),
    ]
